form2
maxkvlenko/html pull request #4
Opened 2022-08-24 21:21 UTC by maxkvlenko

2022-08-25 07:03 UTC, Gaurrus requested changes
Комментарии

2022-08-25 07:12 UTC, Gaurrus requested changes

2022-08-25 07:12 UTC, Gaurrus commented on form2/index.html
> +            <option атрибуты>Старше 40 лет</option>
что за атрибуты?)

2022-08-25 07:12 UTC, Gaurrus commented on form2/index.html
> +        мужской<input name="m" type="radio" value="men"> женский<input name="w" type="radio" value="women">
<input  type="radio" name обычно у радтогруппы у всех одинаковый - а value разные например name='sex' men women

2022-08-25 07:12 UTC, Gaurrus commented on form2/index.html
> +            <option атрибуты>Другое государство</option>
атрибуты

2022-08-25 07:12 UTC, Gaurrus commented on form2/index.html
> +       <p><input type="submit" value="Сброс">  <input type="submit" value="Отправить"></p>
не правильный type  у сброса - reset

2022-08-25 07:12 UTC, Gaurrus commented on form2/index2.html
> +        }
это было в шаблоне или сам писал? если сам то к чему это применяется?

2022-08-25 07:12 UTC, Gaurrus commented on form2/index2.html
> +    <p><input name="m" type="radio" value="pyth"> Python</p>
вот тут сделал правильно

2022-08-25 07:12 UTC, Gaurrus commented on form2/index2.html
> +            <option атрибуты>Могилевская</option>
атрибуты

2022-08-25 07:12 UTC, Gaurrus commented on form2/index2.html
> +        <p><input name="m" type="radio" value="M"> Механика</p>
а тут снова не правильно - name value

2022-08-25 07:12 UTC, Gaurrus commented on form2/index2.html
> +          <label for="engine5"> Метан</label></p>
checkbox надо тоже обязательно name и value

2022-08-25 07:12 UTC, Gaurrus commented on form2/index2.html
> +<p><input type="submit" value="Отправить"> <input type="submit" value="Очистить"></p>
type reset снова

2022-08-25 07:12 UTC, Gaurrus commented on form2/index2.html
> +      <p>Серетное поле:</p>
какое поле?))

2022-08-25 07:12 UTC, Gaurrus commented on form2/index.html
> +       <p>Фото профиля: <input type="submit" value="Обзор..."></p>
можно использовать type="file' если хочешь загружать файл или картинку

2022-08-25 21:22 UTC, maxkvlenko commented on form2/index2.html
> +        }
было в шаблоне, сам пока не умею прописывать)

2022-08-26 09:20 UTC, Gaurrus requested changes

2022-08-26 09:20 UTC, Gaurrus commented on form_html5/index.html
> +<body>
все input надо обернуть в форму form

2022-08-26 09:20 UTC, Gaurrus commented on form_html5/index.html
> +<td>Фамилия</td><td><input name="surname"></td>
перепроверь все имена input - они должны соответствовать именам в script файле - скину в чат скрин куда смотреть

2022-08-26 09:20 UTC, Gaurrus commented on form_html5/index.html
> +<td>Фамилия</td><td><input name="surname"></td>
если всё сделашь правильно - отработает скрипт и выведет алерт с данными

2022-08-29 20:42 UTC, merged